### ISSUE TITLE
Updates...?

### ISSUE THREAD

**Issue by zhengliw** [RaderRMT/Bob#1]
Hi @RaderRMT!

I would love to use Bob as a standalone application. Will you offer builds in the future? And is this project still active? I absolutely love the idea of this project...

**Comment by RaderRMT** [comment]
I am working on side projects to guesstimate how I want to structure my code, what features I want Bob to have, and how they are going to work.
If you want updates (and builds) of those side projects, feel free to join [my Discord server](https://discord.com/invite/zNVkeGdjKt).

**Comment by dairiki-ren** [comment]
will do. thanks!
